### ISSUE TITLE
Unable to load PS3 Save Data

### ISSUE THREAD

**Issue by dobey** [apocalyptech/borderlands2#1]
I've been trying to convert my PS3 save games over to Steam, on Linux. Unfortunately, I can only seem to get the following error:

```
$: python3 ~/Projects/borderlands2/bl2_save_edit.py -b -o json /media/TEST/PS3/SAVEDATA/BLUS30982-SAVE-SAVE0007/SAVE0007.SAV bl2-axton.json

Opening /media/TEST/PS3/SAVEDATA/BLUS30982-SAVE-SAVE0007/SAVE0007.SAV for input file


Opening bl2-axton.json for output file
Preparing decoded savegame file
Something went wrong, but please ensure you have the latest
version from https://github.com/apocalyptech/borderlands2 before
reporting a bug.  Information useful for a report follows:

['$HOME/Projects/borderlands2/bl2_save_edit.py', '-b', '-o', 'json', '/media/TEST/PS3/SAVEDATA/BLUS30982-SAVE-SAVE0007/SAVE0007.SAV', 'bl2-axton.json']

Traceback (most recent call last):
  File "$HOME/Projects/borderlands2/bl2_save_edit.py", line 10, in <module>
    app.run()
  File "$HOME/Projects/borderlands2/borderlands/savefile.py", line 1930, in run
    player = self.unwrap_player_data(save_data)
  File "$HOME/Projects/borderlands2/borderlands/savefile.py", line 977, in unwrap_player_data
    raise BorderlandsError("Invalid save file")
borderlands.savefile.BorderlandsError: Invalid save file

```
Here is a copy of a save file from BL2 that is not working.
[SAVE0007.zip](https://github.com/apocalyptech/borderlands2/files/2751321/SAVE0007.zip)

**Comment by dobey** [comment]
The tool does however seem to work OK with save games created with the Steam version. So as a temporary workaround it seems I can at least cheat and set levels/money to match my console toons, once I've found the same weapons anyway.

**Comment by xcier** [comment]
> 

Edit a PC or you can use brutefoce ps3 to first decrypt the and then convert it to pc with gibbed save editor.

Converting a pc save with gibbed to ps3 you can then convert that save but your save has to be decrypted first or else it will be corrupt 👍
